app:
  - changed-files:
      - any-glob-to-any-file: "src/main/**/*"

workflow:
  - changed-files:
      - any-glob-to-any-file:
          [".github/workflows/**/*.yml", ".github/actions/**/*.yml"]

docs:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
  - head-branch: ["^docs/", docs/]

dependencies:
  - changed-files:
      - any-glob-to-any-file: build.gradle.kts
